stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:git
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.picroup.com:444
  - docker build -t $REGISTRY_REPO:${CI_COMMIT_REF_SLUG} .
  - docker push $REGISTRY_REPO:${CI_COMMIT_REF_SLUG}
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

deploy_staging:
  stage: deploy
  image: kroniak/ssh-client:3.6
  script:
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no $USER_HOST "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.picroup.com:444"
    - ssh $USER_HOST "cd $PROJECT_PATH && docker-compose pull $SERVICE_NAME"
    - ssh $USER_HOST "cd $PROJECT_PATH && docker-compose up -d --no-deps --build $SERVICE_NAME"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success

 
